version: '3.8'

services:
  postgresql:
    container_name: recipes-postgres
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - recipes-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  elasticsearch:
    container_name: recipes-elasticsearch
    image: elastic/elasticsearch:8.9.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.type=single-node

  quarkus:
    container_name: recipes-quarkus
    image: local/default/recipes-quarkus:demo
    depends_on:
     - postgresql
     - elasticsearch
    ports:
      - "9000:9000"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=${POSTGRES_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  recipes-postgres-data:
    external: true