quarkus:
  liquibase:
    change-log: changelog/releases-changelog.yaml
    migrate-at-start: true
    validate-on-migrate: true
  hibernate-search-orm:
    elasticsearch:
      version: 8
  test:
    continuous-testing: DISABLED